# 多智能体异常检测配置文件

# 趋势分析智能体配置
trend_agent:
  trend_analyzer:
    smoothing_factor: 0.1
  physics:
    smoothness_weight: 0.1
  feature_extractor:
    feature_dim: 4
  anomaly_detector:
    threshold: 0.5
    memory_size: 100

# 季节分析智能体配置（待实现）
seasonal_agent:
  seasonal_analyzer:
    period_detection: true
    min_period: 2
    max_period: 100
  frequency:
    fft_size: 1024
    window_type: "hann"
  periodicity:
    min_period: 2
    max_period: 100
    confidence_threshold: 0.7

# 残差分析智能体配置（待实现）
residual_agent:
  residual_analyzer:
    noise_threshold: 0.01
    sparsity_threshold: 0.1
  sparsity:
    sparsity_threshold: 0.1
    l1_penalty: 0.01
  noise_filter:
    filter_type: "gaussian"
    kernel_size: 3
    sigma: 1.0

# 协调智能体配置（待实现）
coordinator_agent:
  decision_engine:
    fusion_method: "weighted_average"
    confidence_weight: 0.7
    time_weight: 0.3
  communication:
    optimization_enabled: true
    max_communication_rounds: 5
  weight_calculator:
    confidence_weight: 0.7
    time_weight: 0.3
    error_penalty: 0.1

# 通信总线配置
communication_bus:
  max_queue_size: 1000
  message_timeout: 5.0
  enable_encryption: false

# 性能监控配置
performance_monitor:
  metrics_collection: true
  detailed_logging: false
  log_interval: 10
  memory_monitoring: true

# 多智能体检测器配置
multi_agent_detector:
  enable_parallel_processing: true
  max_parallel_agents: 4
  timeout: 30.0
  retry_count: 3
